## Tutorial of Numpy

In [13]:
import numpy as np 
import pandas as pd

In [87]:
a = np.array([[1,2,3,5],
             [4,5,6,5],
             [6,7,8,5]])
a

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [6, 7, 8, 5]])

In [118]:
b = np.arange(0, 50, 1)


In [97]:
c = b[b % 2 == 0]
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [100]:
b[b > 21]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
b[(b > 21) & (b < 50) & (b % 2 == 0)]

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [106]:
y = np.ones((2,7)) * 3
y

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [110]:
fu = np.full((2,7), 3)
fu

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [117]:
np.random.randint(0,10,size=(2, 2))


array([[7, 6],
       [4, 2]])

In [119]:
b.argmin()

0

In [120]:
b.argmax()

49

In [125]:
b.itemsize * b.size

400

In [126]:
b.size

50

In [127]:
b.itemsize

8

In [128]:
b.argsort()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [129]:
b[b.argsort()]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [131]:
x = np.random.randint(10, 100, size=20)


array([72, 60, 29, 92, 55, 42, 98, 57, 67, 84, 10, 87, 90, 13, 13, 68, 56,
       14, 18, 99])

In [133]:
np.median(x)

58.5

In [134]:
x.size

20

In [135]:
df = pd.DataFrame([{'element': 'Helium', 'symbol': 'He', 'atom`ic_number': 2},
 {'element': 'Magnesium', 'symbol': 'Mg', 'atomic_number': 12}])

In [139]:
df['element']

0       Helium
1    Magnesium
Name: element, dtype: object

In [141]:
education_s = pd.Series([1000, 2000, 3000, 40, 5000, 1000000], name='price', dtype = float)
education_s

0       1000.0
1       2000.0
2       3000.0
3         40.0
4       5000.0
5    1000000.0
Name: price, dtype: float64

In [142]:
education_s.shape


(6,)

In [146]:
education_s.max(), education_s.min(), education_s.std()

(1000000.0, 40.0, 407350.46859757835)

In [147]:
df = pd.DataFrame([{'a': 1, 'b': 2, 'c': 3}, {'a': 1, 'b': 2, 'c': 4},
{'a': 1, 'b': 100, 'c': 1000}, {'a': 1, 'b': 2, 'c': 3}])

In [148]:
df

a    b     c
0  1    2     3
1  1    2     4
2  1  100  1000
3  1    2     3

### Save in future

In [152]:
df.drop_duplicates()

a    b     c
0  1    2     3
1  1    2     4
2  1  100  1000

In [151]:
df

a    b     c
0  1    2     3
1  1    2     4
2  1  100  1000
3  1    2     3